# -*- coding: utf-8 -*-
"""AI_story generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9_Uro8GQBy-1rf8Uw8qtqRppx7B--rU

# using hugging face
"""

!pip install streamlit transformers torch

!pip install streamlit transformers torch pyngrok

!ngrok config add-authtoken 2zNFIXl4wsCxhSJcu3uIWbLlPF6_5dRP4q3Gs8cG4GTbCEiJ3

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from transformers import pipeline, set_seed
# 
# generator = pipeline('text-generation', model='gpt2')
# set_seed(42)
# 
# st.title("AI Story Generator")
# st.write("Give a story prompt and get a creative short story!")
# 
# prompt = st.text_input("Enter your story prompt:", "A time traveler visits ancient Egypt")
# max_len = st.slider("Choose story length (tokens):", 50, 500, 150)
# 
# if st.button("Generate Story"):
#     with st.spinner("Generating..."):
#         story = generator(prompt, max_length=max_len, num_return_sequences=1)[0]['generated_text']
#         st.subheader("📖 Generated Story:")
#         st.write(story)
#

from pyngrok import ngrok
!pkill streamlit
get_ipython().system_raw('streamlit run app.py &')
public_url = ngrok.connect(addr="8501", proto="http")
print("Access your Streamlit app here 👉", public_url)



